# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    # Files stored in `index.js`
    directory: "../index.js"
    schedule:
      interval: "daily"
      time: "02:00"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "./workflows/actions.yml"
    schedule:
      interval: "daily"