name: BUILD-README
# on: This example uses the push event, so that the jobs run every time someone pushes a change to the repository. 
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
  # runs-on: ubuntu-latest
  #             This means that the job will execute on a fresh virtual machine hosted by GitHub. 

    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [12.x]
    
    
    steps:
    # - uses: actions/checkout@v2
    #              This is an action that checks out your repository and downloads it to the runner, allowing you to run actions against your code

      - name: Write File To README
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install node_modules
        run: npm ci
      - name: Build README File
        run: |- 
          npm run start
          cat README.md
      - name: Commit with Diffs
        run: |- 
          git add .
          # git diff
          git config user.email "readme-bot@johannes-lin.me"
          git config user.name "ReadMe Bot"
          git commit -m ":beers: feat(README.md): Updated README" || echo "No changes detected"
          git push 
